package ru.gdlbo.parcelradar.app.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// region Blue
val BlueLightColors = lightColorScheme(
    primary = Color(0xFF0061A4),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFD1E4FF),
    onPrimaryContainer = Color(0xFF001D36),
    secondary = Color(0xFF535F70),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFD7E3F7),
    onSecondaryContainer = Color(0xFF101C2B),
    tertiary = Color(0xFF6B5778),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFF2DAFF),
    onTertiaryContainer = Color(0xFF251431),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color.White,
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFDFCFF),
    onBackground = Color(0xFF1A1C1E),
    surface = Color(0xFFFDFCFF),
    onSurface = Color(0xFF1A1C1E),
    surfaceVariant = Color(0xFFDFE2EB),
    onSurfaceVariant = Color(0xFF43474E),
    outline = Color(0xFF73777F),
    inverseOnSurface = Color(0xFFF1F0F4),
    inverseSurface = Color(0xFF2F3033),
    inversePrimary = Color(0xFF9ECAFF),
    surfaceTint = Color(0xFF0061A4),
)

val BlueDarkColors = darkColorScheme(
    primary = Color(0xFF9ECAFF),
    onPrimary = Color(0xFF003258),
    primaryContainer = Color(0xFF00497D),
    onPrimaryContainer = Color(0xFFD1E4FF),
    secondary = Color(0xFFBBC7DB),
    onSecondary = Color(0xFF253141),
    secondaryContainer = Color(0xFF3C4858),
    onSecondaryContainer = Color(0xFFD7E3F7),
    tertiary = Color(0xFFD6BEE4),
    onTertiary = Color(0xFF3B2948),
    tertiaryContainer = Color(0xFF523F5F),
    onTertiaryContainer = Color(0xFFF2DAFF),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0D0E0F),
    onBackground = Color(0xFFE2E2E6),
    surface = Color(0xFF0D0E0F),
    onSurface = Color(0xFFC6C6CA),
    surfaceVariant = Color(0xFF43474E),
    onSurfaceVariant = Color(0xFFC3C7CF),
    outline = Color(0xFF8D9199),
    inverseOnSurface = Color(0xFF0D0E0F),
    inverseSurface = Color(0xFFE2E2E6),
    inversePrimary = Color(0xFF0061A4),
    surfaceTint = Color(0xFF9ECAFF),
)
// endregion

// region Red
val RedLightColors = lightColorScheme(
    primary = Color(0xFFB71C1C),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFDAD5),
    onPrimaryContainer = Color(0xFF410001),
    secondary = Color(0xFF775651),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFFFDAD5),
    onSecondaryContainer = Color(0xFF2C1512),
    tertiary = Color(0xFF705C2E),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFFBDFA6),
    onTertiaryContainer = Color(0xFF261A00),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color.White,
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFCFCFC),
    onBackground = Color(0xFF191C1C),
    surface = Color(0xFFFCFCFC),
    onSurface = Color(0xFF191C1C),
    surfaceVariant = Color(0xFFF5DDDA),
    onSurfaceVariant = Color(0xFF534341),
    outline = Color(0xFF857371),
    inverseOnSurface = Color(0xFFF0F1F1),
    inverseSurface = Color(0xFF2E3131),
    inversePrimary = Color(0xFFFFB4A8),
    surfaceTint = Color(0xFFB71C1C),
)

val RedDarkColors = darkColorScheme(
    primary = Color(0xFFFFB4A8),
    onPrimary = Color(0xFF690002),
    primaryContainer = Color(0xFF930004),
    onPrimaryContainer = Color(0xFFFFDAD5),
    secondary = Color(0xFFE7BDB8),
    onSecondary = Color(0xFF442926),
    secondaryContainer = Color(0xFF5D3F3B),
    onSecondaryContainer = Color(0xFFFFDAD5),
    tertiary = Color(0xFFDEC48C),
    onTertiary = Color(0xFF3F2E04),
    tertiaryContainer = Color(0xFF574419),
    onTertiaryContainer = Color(0xFFFBDFA6),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0C0E0E),
    onBackground = Color(0xFFE1E3E2),
    surface = Color(0xFF0C0E0E),
    onSurface = Color(0xFFC4C7C7),
    surfaceVariant = Color(0xFF534341),
    onSurfaceVariant = Color(0xFFD8C2BF),
    outline = Color(0xFFA08C8A),
    inverseOnSurface = Color(0xFF0C0E0E),
    inverseSurface = Color(0xFFE1E3E2),
    inversePrimary = Color(0xFFB71C1C),
    surfaceTint = Color(0xFFFFB4A8),
)
// endregion

// region Yellow
val YellowLightColors = lightColorScheme(
    primary = Color(0xFF6D5E0F),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFF8E287),
    onPrimaryContainer = Color(0xFF221B00),
    secondary = Color(0xFF665E40),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFEEE2BC),
    onSecondaryContainer = Color(0xFF211B04),
    tertiary = Color(0xFF43664E),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFC5ECCE),
    onTertiaryContainer = Color(0xFF00210F),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color.White,
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF1D1B16),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF1D1B16),
    surfaceVariant = Color(0xFFEAE2CF),
    onSurfaceVariant = Color(0xFF4B4739),
    outline = Color(0xFF7C7767),
    inverseOnSurface = Color(0xFFF5F0E7),
    inverseSurface = Color(0xFF32302A),
    inversePrimary = Color(0xFFDBC66E),
    surfaceTint = Color(0xFF6D5E0F),
)

val YellowDarkColors = darkColorScheme(
    primary = Color(0xFFDBC66E),
    onPrimary = Color(0xFF3A3000),
    primaryContainer = Color(0xFF534600),
    onPrimaryContainer = Color(0xFFF8E287),
    secondary = Color(0xFFD1C6A1),
    onSecondary = Color(0xFF363016),
    secondaryContainer = Color(0xFF4E472A),
    onSecondaryContainer = Color(0xFFEEE2BC),
    tertiary = Color(0xFFA9D0B3),
    onTertiary = Color(0xFF143723),
    tertiaryContainer = Color(0xFF2C4E38),
    onTertiaryContainer = Color(0xFFC5ECCE),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0E0D0B),
    onBackground = Color(0xFFE7E2D9),
    surface = Color(0xFF0E0D0B),
    onSurface = Color(0xFFD0C6B4),
    surfaceVariant = Color(0xFF4B4739),
    onSurfaceVariant = Color(0xFFCDC6B4),
    outline = Color(0xFF969080),
    inverseOnSurface = Color(0xFF0E0D0B),
    inverseSurface = Color(0xFFE7E2D9),
    inversePrimary = Color(0xFF6D5E0F),
    surfaceTint = Color(0xFFDBC66E),
)
// endregion

// region Orange
val OrangeLightColors = lightColorScheme(
    primary = Color(0xFF8B5000),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFDCBE),
    onPrimaryContainer = Color(0xFF2C1600),
    secondary = Color(0xFF725A42),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFFFDCBE),
    onSecondaryContainer = Color(0xFF291806),
    tertiary = Color(0xFF58633A),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFDCE8B4),
    onTertiaryContainer = Color(0xFF161E01),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color.White,
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF201B16),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF201B16),
    surfaceVariant = Color(0xFFF2DFD1),
    onSurfaceVariant = Color(0xFF51453A),
    outline = Color(0xFF837468),
    inverseOnSurface = Color(0xFFFAEFE7),
    inverseSurface = Color(0xFF352F2A),
    inversePrimary = Color(0xFFFFB870),
    surfaceTint = Color(0xFF8B5000),
)

val OrangeDarkColors = darkColorScheme(
    primary = Color(0xFFFFB870),
    onPrimary = Color(0xFF4A2800),
    primaryContainer = Color(0xFF693C00),
    onPrimaryContainer = Color(0xFFFFDCBE),
    secondary = Color(0xFFE2C1A4),
    onSecondary = Color(0xFF402D18),
    secondaryContainer = Color(0xFF58432C),
    onSecondaryContainer = Color(0xFFFFDCBE),
    tertiary = Color(0xFFC0CC9A),
    onTertiary = Color(0xFF2B3410),
    tertiaryContainer = Color(0xFF414B24),
    onTertiaryContainer = Color(0xFFDCE8B4),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF100D0B),
    onBackground = Color(0xFFEBE0D9),
    surface = Color(0xFF100D0B),
    onSurface = Color(0xFFD4C4B8),
    surfaceVariant = Color(0xFF51453A),
    onSurfaceVariant = Color(0xFFD5C3B5),
    outline = Color(0xFF9D8E81),
    inverseOnSurface = Color(0xFF100D0B),
    inverseSurface = Color(0xFFEBE0D9),
    inversePrimary = Color(0xFF8B5000),
    surfaceTint = Color(0xFFFFB870),
)
// endregion

// region Purple
val PurpleLightColors = lightColorScheme(
    primary = Color(0xFF7D4E7D),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFD7F5),
    onPrimaryContainer = Color(0xFF320936),
    secondary = Color(0xFF6D5869),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFF6DBEF),
    onSecondaryContainer = Color(0xFF261624),
    tertiary = Color(0xFF82524A),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFFFDAD5),
    onTertiaryContainer = Color(0xFF33110C),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color.White,
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF1E1A1D),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF1E1A1D),
    surfaceVariant = Color(0xFFEDDEE8),
    onSurfaceVariant = Color(0xFF4D444C),
    outline = Color(0xFF7F747C),
    inverseOnSurface = Color(0xFFF8EEF3),
    inverseSurface = Color(0xFF342F32),
    inversePrimary = Color(0xFFECB2EB),
    surfaceTint = Color(0xFF7D4E7D),
)

val PurpleDarkColors = darkColorScheme(
    primary = Color(0xFFECB2EB),
    onPrimary = Color(0xFF4A204D),
    primaryContainer = Color(0xFF633764),
    onPrimaryContainer = Color(0xFFFFD7F5),
    secondary = Color(0xFFD9BFD3),
    onSecondary = Color(0xFF3D2B3A),
    secondaryContainer = Color(0xFF544151),
    onSecondaryContainer = Color(0xFFF6DBEF),
    tertiary = Color(0xFFF6B8AD),
    onTertiary = Color(0xFF4C251F),
    tertiaryContainer = Color(0xFF673B34),
    onTertiaryContainer = Color(0xFFFFDAD5),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0F0D0E),
    onBackground = Color(0xFFE9E0E4),
    surface = Color(0xFF0F0D0E),
    onSurface = Color(0xFFCEC4C9),
    surfaceVariant = Color(0xFF4D444C),
    onSurfaceVariant = Color(0xFFD0C3CC),
    outline = Color(0xFF998D96),
    inverseOnSurface = Color(0xFF0F0D0E),
    inverseSurface = Color(0xFFE9E0E4),
    inversePrimary = Color(0xFF7D4E7D),
    surfaceTint = Color(0xFFECB2EB),
)
// endregion

// region Pink
val PinkLightColors = lightColorScheme(
    primary = Color(0xFF984061),
    onPrimary = Color.White,
    primaryContainer = Color(0xFFFFD9E2),
    onPrimaryContainer = Color(0xFF3E001D),
    secondary = Color(0xFF74565F),
    onSecondary = Color.White,
    secondaryContainer = Color(0xFFFFD9E2),
    onSecondaryContainer = Color(0xFF2B151C),
    tertiary = Color(0xFF7C5635),
    onTertiary = Color.White,
    tertiaryContainer = Color(0xFFFFDCC1),
    onTertiaryContainer = Color(0xFF2E1500),
    error = Color(0xFFBA1A1A),
    errorContainer = Color(0xFFFFDAD6),
    onError = Color.White,
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF201A1B),
    surface = Color(0xFFFFFBFF),
    onSurface = Color(0xFF201A1B),
    surfaceVariant = Color(0xFFF2DDE1),
    onSurfaceVariant = Color(0xFF514347),
    outline = Color(0xFF837377),
    inverseOnSurface = Color(0xFFFAEEEF),
    inverseSurface = Color(0xFF352F30),
    inversePrimary = Color(0xFFFFB1C8),
    surfaceTint = Color(0xFF984061),
)

val PinkDarkColors = darkColorScheme(
    primary = Color(0xFFFFB1C8),
    onPrimary = Color(0xFF5E1133),
    primaryContainer = Color(0xFF7B2949),
    onPrimaryContainer = Color(0xFFFFD9E2),
    secondary = Color(0xFFE3BDC6),
    onSecondary = Color(0xFF422931),
    secondaryContainer = Color(0xFF5A3F47),
    onSecondaryContainer = Color(0xFFFFD9E2),
    tertiary = Color(0xFFEFBD94),
    onTertiary = Color(0xFF48290B),
    tertiaryContainer = Color(0xFF623F20),
    onTertiaryContainer = Color(0xFFFFDCC1),
    error = Color(0xFFFFB4AB),
    errorContainer = Color(0xFF93000A),
    onError = Color(0xFF690005),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF100D0D),
    onBackground = Color(0xFFEBE0E1),
    surface = Color(0xFF100D0D),
    onSurface = Color(0xFFD5C4C6),
    surfaceVariant = Color(0xFF514347),
    onSurfaceVariant = Color(0xFFD5C2C6),
    outline = Color(0xFF9E8C90),
    inverseOnSurface = Color(0xFF100D0D),
    inverseSurface = Color(0xFFEBE0E1),
    inversePrimary = Color(0xFF984061),
    surfaceTint = Color(0xFFFFB1C8),
)
// endregion